# Generated by Django 4.2.4 on 2023-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='min_read',
            field=models.IntegerField(default=1),
        ),
    ]
