# Generated by Django 4.2.4 on 2023-09-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='nytPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('cover_img', models.ImageField(upload_to='post_images')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('url', models.URLField()),
                ('published_date', models.DateTimeField()),
                ('description', models.TextField(blank='False', default='this is a description')),
                ('min_read', models.IntegerField(default=1)),
            ],
        ),
    ]
